### ISSUE TITLE
Windows - system restart

### ISSUE THREAD

**Issue by premnathj** [pm2-hive/pm2-logrotate#33]
Hi,

I have installed the pm2-logrotate and configured it in the windows environment. Everything works fine until I restart the system. After the reboot, I don't see the pm2-logrotate is running any more.
Please suggest what is the workaround. 

Thanks

**Comment by vmarchaud** [comment]
Its because pm2 isnt persistent across reboot my default, you need to ask your OS to start it after you reboot it, there are several tools to do this : [this one](https://www.npmjs.com/package/pm2-windows-startup) for example, or you can do it directly with the Windows registry i suppose.
More info on this here : https://github.com/Unitech/pm2/issues/1079
